name: Ansible Checks

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ansible_checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed for progressive mode to work
      
      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@main
      
      - name: Check Tag Version Syntax
        uses: smithsonite/checkalltags@v1
